Repository clubpog/POG_server, pull requests merged in 2022-05, with the labels that each got.

#171 [refac]: 테스트 서버 소환사 즐겨찾기 API transaction 설정 통합
  apps/api/src/favoriteSummoner/FavoriteSummonerApiService.ts
  apps/api/test/e2e/FavoriteSummonerApiController.e2e.spec.ts
  apps/api/test/testUtils.ts
  apps/api/test/unit/domain/favoriteSummoner/FavoriteSummonerApiService.spec.ts
  libs/entity/test/stub/ConnectionStub.ts
  libs/entity/test/stub/ManagerStub.ts
  libs/entity/test/stub/QueryRunnerStub.ts
Labels: 🧑🏻‍💻 개발자 상수, 🤔 Refac

#173 [remove]: AB 테스트 수정으로 인한 불필요한 비즈니스 로직 제거
  apps/push/src/push/PushApiService.ts
  apps/push/src/push/PushApiTask.ts
  apps/push/src/push/interface/IPushApiTask.ts
Labels: 🛠 Fix, 🧑🏻‍💻 개발자 상수

#174 [fix]: Push AB 테스트 중 B안에 해당하는 푸시 테스트 적용
  apps/push/src/push/PushApiService.ts
Labels: 🛠 Fix, 🧑🏻‍💻 개발자 상수

#175 [HOTFIX]: 푸시 AB 테스트 topic 변경
  libs/common-config/src/job/push/PushJobService.ts
Labels: 🎤 HOTFIX, 🧑🏻‍💻 개발자 상수

#178 [chore]: Dev, Prod 자동 배포 구축 및 브랜치 전략 정리 완료
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production-api.yml
  .github/workflows/deploy-production-push.yml
  .github/workflows/integration-test.yml
  apps/api/src/ApiAppModule.ts
  apps/api/src/favoriteSummoner/FavoriteSummonerApiService.ts
  apps/api/src/main.ts
  apps/api/test/ApiTestAppModule.ts
  apps/api/test/FavoriteSummonerApiTestModule.ts
  apps/api/test/e2e/FavoriteSummonerApiController.e2e.spec.ts
  apps/api/test/testUtils.ts
  apps/api/test/unit/domain/favoriteSummoner/FavoriteSummonerApiService.spec.ts
  apps/api/tsconfig.app.json
  apps/push/src/PushAppModule.ts
  apps/push/src/main.ts
  apps/push/src/push/PushApiConsumer.ts
  apps/push/src/push/PushApiModule.ts
  apps/push/src/push/PushApiService.ts
  apps/push/src/push/PushApiTask.ts
  apps/push/src/push/interface/IPushApiTask.ts
  apps/push/src/summonerRecord/SummonerRecordApiModule.ts
  apps/push/src/summonerRecord/SummonerRecordApiQueryRepository.ts
  apps/push/test/ApiTestAppModule.ts
  apps/push/test/unit/domain/push/PushApiService.spec.ts
  apps/push/test/unit/stub/push/PushApiTaskStub.ts
  apps/push/test/unit/stub/summonerRecord/SummonerRecordApiQueryRepositoryStub.ts
  apps/push/tsconfig.app.json
  appspec.yml
  libs/common-config/src/config/validationSchema.ts
  libs/common-config/src/enum/ApplicationInjectionToken.ts
  libs/common-config/src/filter/HttpExceptionFilter.ts
  libs/common-config/src/job/push/PushJobService.ts
  libs/common-config/src/job/push/test/stub/PushJobServiceStub.ts
  libs/common-config/src/job/riot/RiotApiJobService.ts
  libs/common-config/src/job/riot/interface/IRiotApiJobService.ts
  libs/common-config/src/job/riot/test/stub/RiotApiJobServiceStub.ts
  libs/common-config/src/job/slack/SlackService.ts
  libs/common-config/src/job/slack/interface/ISlackService.ts
  libs/common-config/src/sentry/SentryModule.ts
  libs/common-config/src/setNestApp.ts
  libs/entity/config/configService.ts
  libs/entity/queue/src/lib/BullConstant.ts
  libs/entity/queue/src/lib/BullModule.ts
  libs/entity/queue/src/lib/BullService.ts
  libs/entity/queue/src/lib/BullTaskMetadataExplorer.ts
  libs/entity/queue/src/lib/BullTaskRegisterService.ts
  libs/entity/queue/src/lib/BullUtils.ts
  libs/entity/queue/src/lib/index.ts
  libs/entity/queue/src/lib/interface/IBullService.ts
  libs/entity/queue/test/stub/BullServiceStub.ts
  libs/entity/test/stub/ConnectionStub.ts
  libs/entity/test/stub/ManagerStub.ts
  libs/entity/test/stub/QueryRunnerStub.ts
  libs/entity/test/stub/RedisServiceStub.ts
  package-lock.json
  package.json
  scripts/before-deploy.sh
Labels: ⭐️ Chore, 🧑🏻‍💻 개발자 찬기

#176 [chore]: Dev, Prod 자동 배포 구축 및 브랜치 전략 정리 완료
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production-api.yml
  .github/workflows/deploy-production-push.yml
  .github/workflows/integration-test.yml
  apps/api/src/ApiAppModule.ts
  apps/api/src/favoriteSummoner/FavoriteSummonerApiService.ts
  apps/api/src/main.ts
  apps/api/test/ApiTestAppModule.ts
  apps/api/test/FavoriteSummonerApiTestModule.ts
  apps/api/test/e2e/FavoriteSummonerApiController.e2e.spec.ts
  apps/api/test/testUtils.ts
  apps/api/test/unit/domain/favoriteSummoner/FavoriteSummonerApiService.spec.ts
  apps/api/tsconfig.app.json
  apps/push/src/PushAppModule.ts
  apps/push/src/main.ts
  apps/push/src/push/PushApiConsumer.ts
  apps/push/src/push/PushApiModule.ts
  apps/push/src/push/PushApiService.ts
  apps/push/src/push/PushApiTask.ts
  apps/push/src/push/interface/IPushApiTask.ts
  apps/push/src/summonerRecord/SummonerRecordApiModule.ts
  apps/push/src/summonerRecord/SummonerRecordApiQueryRepository.ts
  apps/push/test/ApiTestAppModule.ts
  apps/push/test/unit/domain/push/PushApiService.spec.ts
  apps/push/test/unit/stub/push/PushApiTaskStub.ts
  apps/push/test/unit/stub/summonerRecord/SummonerRecordApiQueryRepositoryStub.ts
  apps/push/tsconfig.app.json
  appspec.yml
  libs/common-config/src/config/validationSchema.ts
  libs/common-config/src/enum/ApplicationInjectionToken.ts
  libs/common-config/src/filter/HttpExceptionFilter.ts
  libs/common-config/src/job/push/PushJobService.ts
  libs/common-config/src/job/push/test/stub/PushJobServiceStub.ts
  libs/common-config/src/job/riot/RiotApiJobService.ts
  libs/common-config/src/job/riot/interface/IRiotApiJobService.ts
  libs/common-config/src/job/riot/test/stub/RiotApiJobServiceStub.ts
  libs/common-config/src/job/slack/SlackService.ts
  libs/common-config/src/job/slack/interface/ISlackService.ts
  libs/common-config/src/sentry/SentryModule.ts
  libs/common-config/src/setNestApp.ts
  libs/entity/config/configService.ts
  libs/entity/queue/src/lib/BullConstant.ts
  libs/entity/queue/src/lib/BullModule.ts
  libs/entity/queue/src/lib/BullService.ts
  libs/entity/queue/src/lib/BullTaskMetadataExplorer.ts
  libs/entity/queue/src/lib/BullTaskRegisterService.ts
  libs/entity/queue/src/lib/BullUtils.ts
  libs/entity/queue/src/lib/index.ts
  libs/entity/queue/src/lib/interface/IBullService.ts
  libs/entity/queue/test/stub/BullServiceStub.ts
  libs/entity/test/stub/ConnectionStub.ts
  libs/entity/test/stub/ManagerStub.ts
  libs/entity/test/stub/QueryRunnerStub.ts
  libs/entity/test/stub/RedisServiceStub.ts
  package-lock.json
  package.json
  scripts/before-deploy.sh
Labels: ⭐️ Chore, 🧑🏻‍💻 개발자 찬기

#177 [chore]: Dev, Prod 자동 배포 구축 및 브랜치 전략 정리 완료
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production-api.yml
  .github/workflows/deploy-production-push.yml
  .github/workflows/integration-test.yml
  apps/api/src/ApiAppModule.ts
  apps/api/src/favoriteSummoner/FavoriteSummonerApiService.ts
  apps/api/src/main.ts
  apps/api/test/ApiTestAppModule.ts
  apps/api/test/FavoriteSummonerApiTestModule.ts
  apps/api/test/e2e/FavoriteSummonerApiController.e2e.spec.ts
  apps/api/test/testUtils.ts
  apps/api/test/unit/domain/favoriteSummoner/FavoriteSummonerApiService.spec.ts
  apps/api/tsconfig.app.json
  apps/push/src/PushAppModule.ts
  apps/push/src/main.ts
  apps/push/src/push/PushApiConsumer.ts
  apps/push/src/push/PushApiModule.ts
  apps/push/src/push/PushApiService.ts
  apps/push/src/push/PushApiTask.ts
  apps/push/src/push/interface/IPushApiTask.ts
  apps/push/src/summonerRecord/SummonerRecordApiModule.ts
  apps/push/src/summonerRecord/SummonerRecordApiQueryRepository.ts
  apps/push/test/ApiTestAppModule.ts
  apps/push/test/unit/domain/push/PushApiService.spec.ts
  apps/push/test/unit/stub/push/PushApiTaskStub.ts
  apps/push/test/unit/stub/summonerRecord/SummonerRecordApiQueryRepositoryStub.ts
  apps/push/tsconfig.app.json
  appspec.yml
  libs/common-config/src/config/validationSchema.ts
  libs/common-config/src/enum/ApplicationInjectionToken.ts
  libs/common-config/src/filter/HttpExceptionFilter.ts
  libs/common-config/src/job/push/PushJobService.ts
  libs/common-config/src/job/push/test/stub/PushJobServiceStub.ts
  libs/common-config/src/job/riot/RiotApiJobService.ts
  libs/common-config/src/job/riot/interface/IRiotApiJobService.ts
  libs/common-config/src/job/riot/test/stub/RiotApiJobServiceStub.ts
  libs/common-config/src/job/slack/SlackService.ts
  libs/common-config/src/job/slack/interface/ISlackService.ts
  libs/common-config/src/sentry/SentryModule.ts
  libs/common-config/src/setNestApp.ts
  libs/entity/config/configService.ts
  libs/entity/queue/src/lib/BullConstant.ts
  libs/entity/queue/src/lib/BullModule.ts
  libs/entity/queue/src/lib/BullService.ts
  libs/entity/queue/src/lib/BullTaskMetadataExplorer.ts
  libs/entity/queue/src/lib/BullTaskRegisterService.ts
  libs/entity/queue/src/lib/BullUtils.ts
  libs/entity/queue/src/lib/index.ts
  libs/entity/queue/src/lib/interface/IBullService.ts
  libs/entity/queue/test/stub/BullServiceStub.ts
  libs/entity/test/stub/ConnectionStub.ts
  libs/entity/test/stub/ManagerStub.ts
  libs/entity/test/stub/QueryRunnerStub.ts
  libs/entity/test/stub/RedisServiceStub.ts
  package-lock.json
  package.json
  scripts/before-deploy.sh
Labels: ⭐️ Chore, 🧑🏻‍💻 개발자 찬기

#179 [fix]: 푸시 AB 테스트 경우의 수 추가
  apps/push/src/push/PushApiService.ts
  apps/push/src/push/PushApiTask.ts
  apps/push/src/push/interface/IPushApiTask.ts
  apps/push/test/unit/stub/push/PushApiTaskStub.ts
  libs/common-config/src/job/push/PushJobService.ts
  libs/common-config/src/job/push/test/stub/PushJobServiceStub.ts
Labels: 🛠 Fix, 🧑🏻‍💻 개발자 상수

#180 [HOTFIX]: 푸시알림 승리로만 가는 문제 해결
  apps/push/src/push/PushApiService.ts
Labels: 🎤 HOTFIX, 🧑🏻‍💻 개발자 상수

#186 [feat]: 소환사 전적 갱신 조회 API 도입
  apps/api/src/changedTier/ChangedTierApiModule.ts
  apps/api/src/changedTier/ChangedTierApiQueryRepository.ts
  apps/api/src/changedTier/interface/IChangedTierReadSuccess.ts
  apps/api/src/favoriteSummoner/FavoriteSummonerApiController.ts
  apps/api/src/favoriteSummoner/FavoriteSummonerApiModule.ts
  apps/api/src/favoriteSummoner/FavoriteSummonerApiService.ts
  apps/api/src/favoriteSummoner/dto/FavoriteSummonerChangedTierQuery.dto.ts
  apps/api/src/favoriteSummoner/dto/FavoriteSummonerChangedTierReq.dto.ts
  apps/api/src/favoriteSummoner/dto/FavoriteSummonerChangedTierRes.dto.ts
  apps/api/test/FavoriteSummonerApiTestModule.ts
  apps/api/test/e2e/FavoriteSummonerApiController.e2e.spec.ts
  apps/api/test/integration/domain/favoriteSummoner/FavoriteSummonerApiService.int.spec.ts
  apps/push/src/changedTier/ChangedTierApiModule.ts
  apps/push/src/changedTier/ChangedTierApiQueryRepository.ts
  apps/push/src/push/PushApiModule.ts
  apps/push/src/push/PushApiService.ts
  apps/push/src/push/dto/PushRiotApi.ts
  apps/push/src/summonerRecord/SummonerRecordApiQueryRepository.ts
  apps/push/test/unit/stub/summonerRecord/SummonerRecordApiQueryRepositoryStub.ts
  libs/cache/EventStoreService.ts
  libs/common-config/src/abstract/page.request.ts
  libs/common-config/src/job/riot/RiotApiJobService.ts
  libs/common-config/src/job/riot/interface/IRiotApiJobService.ts
  libs/common-config/src/job/riot/test/stub/RiotApiJobServiceStub.ts
  libs/common-config/src/response/swagger/domain/favoriteSummoner/FavoriteSummonerChangedTierReadSuccess.ts
  libs/entity/config/migrateConfig.ts
  libs/entity/migrations/1653285106176-CreateChangedTier.ts
  libs/entity/migrations/1653445543224-CreateChangedTier2.ts
  libs/entity/migrations/1653446832507-CreateChangedTier3.ts
  libs/entity/migrations/1653448743659-CreateChangedTier4.ts
  libs/entity/migrations/1653490882415-CreateChangedTier6.ts
  libs/entity/src/domain/changedTier/ChangedTier.entity.ts
  libs/entity/src/domain/changedTier/ChangedTierModule.ts
  libs/entity/src/domain/changedTier/ChangedTierPagination.ts
  libs/entity/src/domain/summonerRecord/SummonerRecordPuuid.ts
  package.json
Labels: 🔥 Feat, 🧑🏻‍💻 개발자 상수

#185 [chore]: Sonar Cloud 분석 Tool 추가
  .github/workflows/integration-test.yml
  package.json
  sonar-project.properties
Labels: ⭐️ Chore, 🧑🏻‍💻 개발자 찬기
